// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// accumulate_evidence_ddm_2b
List accumulate_evidence_ddm_2b(NumericVector A_upper, NumericVector A_lower, NumericVector V, NumericVector Z, NumericVector ndt, double max_t, double dt, int max_reached, String noise_mechanism, Function noise_func);
RcppExport SEXP _eam_accumulate_evidence_ddm_2b(SEXP A_upperSEXP, SEXP A_lowerSEXP, SEXP VSEXP, SEXP ZSEXP, SEXP ndtSEXP, SEXP max_tSEXP, SEXP dtSEXP, SEXP max_reachedSEXP, SEXP noise_mechanismSEXP, SEXP noise_funcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A_upper(A_upperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type A_lower(A_lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ndt(ndtSEXP);
    Rcpp::traits::input_parameter< double >::type max_t(max_tSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type max_reached(max_reachedSEXP);
    Rcpp::traits::input_parameter< String >::type noise_mechanism(noise_mechanismSEXP);
    Rcpp::traits::input_parameter< Function >::type noise_func(noise_funcSEXP);
    rcpp_result_gen = Rcpp::wrap(accumulate_evidence_ddm_2b(A_upper, A_lower, V, Z, ndt, max_t, dt, max_reached, noise_mechanism, noise_func));
    return rcpp_result_gen;
END_RCPP
}
// accumulate_evidence_ddm
List accumulate_evidence_ddm(NumericVector A, NumericVector V, NumericVector Z, NumericVector ndt, double max_t, double dt, int max_reached, String noise_mechanism, Function noise_func);
RcppExport SEXP _eam_accumulate_evidence_ddm(SEXP ASEXP, SEXP VSEXP, SEXP ZSEXP, SEXP ndtSEXP, SEXP max_tSEXP, SEXP dtSEXP, SEXP max_reachedSEXP, SEXP noise_mechanismSEXP, SEXP noise_funcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ndt(ndtSEXP);
    Rcpp::traits::input_parameter< double >::type max_t(max_tSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type max_reached(max_reachedSEXP);
    Rcpp::traits::input_parameter< String >::type noise_mechanism(noise_mechanismSEXP);
    Rcpp::traits::input_parameter< Function >::type noise_func(noise_funcSEXP);
    rcpp_result_gen = Rcpp::wrap(accumulate_evidence_ddm(A, V, Z, ndt, max_t, dt, max_reached, noise_mechanism, noise_func));
    return rcpp_result_gen;
END_RCPP
}
// accumulate_evidence_lca_gi
List accumulate_evidence_lca_gi(NumericVector A, NumericVector V, NumericVector Z, NumericVector ndt, NumericVector beta, NumericVector k, double max_t, double dt, int max_reached, Function noise_func);
RcppExport SEXP _eam_accumulate_evidence_lca_gi(SEXP ASEXP, SEXP VSEXP, SEXP ZSEXP, SEXP ndtSEXP, SEXP betaSEXP, SEXP kSEXP, SEXP max_tSEXP, SEXP dtSEXP, SEXP max_reachedSEXP, SEXP noise_funcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ndt(ndtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type max_t(max_tSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type max_reached(max_reachedSEXP);
    Rcpp::traits::input_parameter< Function >::type noise_func(noise_funcSEXP);
    rcpp_result_gen = Rcpp::wrap(accumulate_evidence_lca_gi(A, V, Z, ndt, beta, k, max_t, dt, max_reached, noise_func));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eam_accumulate_evidence_ddm_2b", (DL_FUNC) &_eam_accumulate_evidence_ddm_2b, 10},
    {"_eam_accumulate_evidence_ddm", (DL_FUNC) &_eam_accumulate_evidence_ddm, 9},
    {"_eam_accumulate_evidence_lca_gi", (DL_FUNC) &_eam_accumulate_evidence_lca_gi, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_eam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
