# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate evidence accumulation in a two-bound drift-diffusion model
#' @keywords internal
#'
accumulate_evidence_ddm_2b <- function(A_upper, A_lower, V, Z, ndt, max_t, dt, max_reached, noise_mechanism = "add", noise_func = NULL) {
    .Call(`_eam_accumulate_evidence_ddm_2b`, A_upper, A_lower, V, Z, ndt, max_t, dt, max_reached, noise_mechanism, noise_func)
}

#' Simulate evidence accumulation in a drift-diffusion model
#' @keywords internal
#'
accumulate_evidence_ddm <- function(A, V, Z, ndt, max_t, dt, max_reached, noise_mechanism = "add", noise_func = NULL) {
    .Call(`_eam_accumulate_evidence_ddm`, A, V, Z, ndt, max_t, dt, max_reached, noise_mechanism, noise_func)
}

#' Simulate evidence accumulation in a leaky competing accumulator model with
#' Global Inhibition (LCA-GI)
#' @keywords internal
#'
accumulate_evidence_lca_gi <- function(A, V, Z, ndt, beta, k, max_t, dt, max_reached, noise_func = NULL) {
    .Call(`_eam_accumulate_evidence_lca_gi`, A, V, Z, ndt, beta, k, max_t, dt, max_reached, noise_func)
}

